---
- name: compile
  image: node18
  command: cd src; yarn && yarn build
  wait: true
  emails: onfailure
- name: update
  command: cd src; yarn start
  image: node18
  schedule: "*/15 * * * *"
  emails: onfailure
