---
- name: compile
  image: tf-node16
  command: cd src; yarn && yarn build
  wait: true
  emails: onfailure
- name: update
  command: cd src; yarn start
  image: tf-node16
  schedule: "*/15 * * * *"
  emails: onfailure
