name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        env:
          SSH_KEY: ${{ secrets.GIT_CD_SSH_KEY }}
        run: |
          echo "$SSH_KEY" >> ssh_key
          ssh -i ssh_key -o StrictHostKeyChecking=no xtex@login.toolforge.org become new-userbox-log bash -c "cd src; bash ./deploy/update.sh"
